### ISSUE TITLE
클래스 상세 페이지 안드로이드 브릿지 연결

### ISSUE THREAD

**Issue by xodms0309** [YAPP-Github/20th-ALL-Rounder-Team-2-Web#125]
### ISSUE
- Type: feature
- Page: lecture-detail

### TODO
1. [ ] ~~(코치) 가능한 시간대가 없는 경우 클래스 등록하기 화면으로 이동~~
2. [x] 가능한 시간대가 없는 경우 case 삭제
3. [x] (코치) 매칭 신청인 확인 버튼 클릭 시 해당 페이지로 이동

### ETC
기타 사항
