### ISSUE TITLE
매칭신청서 box width 제거

### ISSUE THREAD

**Issue by xodms0309** [YAPP-Github/20th-ALL-Rounder-Team-2-Web#147]
### ISSUE
- Type: style
- Page: matching

### TODO
1. [x] 스텝별 안내 문구 박스 width 제거
2. [x] 스케줄 박스 width 제거
3. [x] text area width 제거

### ETC
기타 사항
