### ISSUE TITLE
홈(메인) 페이지 클래스 리스트 API 연동

### ISSUE THREAD

**Issue by useonglee** [YAPP-Github/20th-ALL-Rounder-Team-2-Web#48]
### ISSUE
- Type: feature
- Page: home

### TODO
- [x] react-query 전역 캐시 값 설정
- [x] react-query를 사용해서 최근 등록된 클래스 API 연동 후 리스트 조회 기능 구현
- [x] ~~리스트 조회 기능 무한 스크롤 기능 구현 -> 검색 기능, 카테고리 상세 조회 기능에서 사용 예정~~
- [x]  테스트 코드 작성

### ETC
기타 사항
