### ISSUE TITLE
최근 등록된 클래스 검색 기능 추가

### ISSUE THREAD

**Issue by useonglee** [YAPP-Github/20th-ALL-Rounder-Team-2-Web#52]
### ISSUE
- Type: feature
- Page: home

### TODO
1. [x] 검색 시 검색 레이아웃 UI 구현
2. [x] 클래스 검색 기능 추가
3. [x] 검색된 클래스 목록 인피니티 스크롤 기능 적용 

### ETC
기타 사항
