### ISSUE TITLE
클래스 상세 페이지 유저 타입과 상태에 따른 CTA 버튼 변경

### ISSUE THREAD

**Issue by xodms0309** [YAPP-Github/20th-ALL-Rounder-Team-2-Web#86]
### ISSUE
- Type: feature
- Page: lecture-detail

### TODO
1. [x] ~~`coach`의 경우 운영클래스 api 호출~~
2. [x] ~~`player`의 경우 수강클래스 api 호출~~
3. [x] 유저 type 검증 코드 작성
4. [x] player state : `NONE`, `ON_BOARD`, `ON_GOING` , `DONE`에 따른 CTA 버튼 변경
   - 가능한 시간이 없는 경우: CTA 비활성화 && 매칭 신청하기
   - 가능한 시간이 있는 경우
      - `NONE` (`REQUEST`) : CTA 활성화 && 매칭 신청하기
      -  `ON_BOARD`, `ON_GOING` : CTA 비활성화 && 매칭 신청하기
      -  `DONE`: CTA 활성화 && 클래스 후기 작성하기
5. [x] coach state
     - 가능한 시간이 없는 경우: CTA 활성화 && 가능한 시간을 등록해주세요
     - 가능한 시간이 있는 경우: CTA 활성화 && 매칭 신청인 보기(매칭신청인수)

### ETC
기타 사항
